baseURL = "https://warframeblog.com/"
languageCode = "en-us"
title = "Warframe Blog"
theme = "hesti"
paginate = 10
enableRobotsTXT = true
DefaultContentLanguage = "en"
googleAnalytics = "UA-108446512-1"
canonifyURLs = true
enableInlineShortcodes = true
[social]
	twitter = "warframeblog"
	facebook = "warframeblog"
[params]
	favicon = "favicon.ico"
	title = "Warframe blog"
	description = "Useful Warframe guides, warframe and weapon builds, Warframe resource farming guides and latest news about Warframe updates."
	seoTitle = "Warframe blog - Latest news, best builds, and fresh guides"
	googleAdsense = "ca-pub-2537852360607581"
	image = "/images/warframe-blog-header.jpg"
	locale = "en_US"
	navClasses = "navbar navbar-default navbar-fixed-top navbar-color-on-scroll navbar-transparent hestia_left"
[taxonomies]
	category = "categories"
[permalinks]
	categories = "/:slug/"
	warframes = "/:section/:slug/"
[sitemap]
	changefreq = "daily"
	filename = "sitemap.xml"
	priority = 0.5
[related]
	[[related.indices]]
		name  = "categories"
		weight = 80
	[[related.indices]]
		name  = "tags"
		weight = 100
[menu]
	[[menu.main]]
		identifier = "news"
		name = "News"
		url = "/warframe-news/"
		weight = 10
	[[menu.main]]
		identifier = "guides"
		name = "Guides"
		url = "/guides/"
		weight = 20
	[[menu.main]]
		parent = "guides"
		name = "Warframe Fortuna"
		url = "/fortuna/"
		weight = 21
	[[menu.main]]
		parent = "guides"
		name = "How To Get Primes"
		url = "/primes/"
		weight = 22
	[[menu.main]]
		parent = "guides"
		name = "Warframes"
		url = "/warframes/"
		weight = 23
	[[menu.main]]
		identifier = "farming"
		name = "Farming"
		url = "/farming/"
		weight = 30
	[[menu.main]]
		identifier = "builds"
		name = "Builds"
		url = "/builds/"
		weight = 40
	[[menu.main]]
		parent = "builds"
		name = "Warframe Builds"
		url = "/warframe-builds/"
		weight = 41
	[[menu.main]]
		parent = "builds"
		name = "Primary Weapon Builds"
		url = "/primary-weapon-builds/"
		weight = 42
	[[menu.main]]
		parent = "builds"
		name = "Secondary Weapon Builds"
		url = "/secondary-weapon-builds/"
		weight = 43
	[[menu.main]]
		parent = "builds"
		name = "Melee Weapon Builds"
		url = "/melee-weapon-builds/"
		weight = 44


	[[menu.builds]]
		name = "All"
		url = "/builds/"
		weight = 10
	[[menu.builds]]
		name = "Warframe Builds"
		url = "/warframe-builds/"
		weight = 20
	[[menu.builds]]
		name = "Primary Weapon Builds"
		url = "/primary-weapon-builds/"
		weight = 30
	[[menu.builds]]
		name = "Secondary Weapon Builds"
		url = "/secondary-weapon-builds/"
		weight = 40
	[[menu.builds]]
		name = "Melee Weapon Builds"
		url = "/melee-weapon-builds/"
		weight = 50