baseURL = "https://seasonedreviews.com/"
languageCode = "en-us"
title = "Warframe Blog"
theme = "hestia"
paginate = 10
enableRobotsTXT = true
DefaultContentLanguage = "en"
googleAnalytics = "UA-108446512-1"
canonifyURLs = true
[social]
	twitter = "warframeblog"
	facebook = "warframeblog"
[params]
	favicon = "favicon.ico"
	title = "Warframe blog"
	description = "Useful Warframe guides, warframe and weapon builds, Warframe resource farming guides and latest news about Warframe updates."
	seoTitle = "Warframe blog - Latest news, best builds, and fresh guides"
	googleAdsense = "ca-pub-2537852360607581"
	image = "/images/warframe-blog-header.jpg"
	locale = "en_US"
[taxonomies]
	category = "categories"
[permalinks]
	categories = "/:slug/"
[sitemap]
	changefreq = "daily"
	filename = "sitemap.xml"
	priority = 0.5
[related]
	[[related.indices]]
		name  = "categories"
		weight = 80
	[[related.indices]]
		name  = "tags"
		weight = 100