version: 2

jobs:
    checkout:
        docker:
            - image: cibuilds/hugo:latest
        working_directory: ~/warframeblog
        steps:
            - run:
                name: Update git
                command: apk update && apk add git
            - run: git --version
            - add_ssh_keys:
                fingerprint:
                    - "4d:bc:43:fc:36:51:1a:8c:4b:a9:2d:15:a6:8d:d8:34"
            - run: git config --global user.email bot@warframeblog.com
            - run: git config --global user.name CircleCI
            - checkout
            - run:
                name: Checkout submodules
                command: git submodule sync && git submodule update --init
            - persist_to_workspace:
                root: /root/warframeblog
                paths: ./
    build:
        docker:
            - image: cibuilds/hugo:latest
        working_directory: ~/warframeblog
        steps:
            - attach_workspace:
                at: /root/warframeblog
            - run: ls -l
            - run: cd /themes/hestia
            - run: ls -l 
workflows:
  version: 2
  checkout_and_build:
    jobs:
      - checkout:
          filters:
            branches:
              only: develop
      - build:
          requires:
            - checkout
          filters:
            branches:
              only: develop