version: 2

jobs:
    build:
        docker:
            - image: node:8.12.0-alpine
        working_directory: ~/warframeblog
        steps:
            - run:
                name: Update git
                command: apk update && apk add git
            - run: git --version
            - run:
                name: Install OpenSSH
                command: apk update && apk add openssh
            - add_ssh_keys:
                fingerprint:
                    - "4d:bc:43:fc:36:51:1a:8c:4b:a9:2d:15:a6:8d:d8:34"
            - run: git config --global user.email bot@warframeblog.com
            - run: git config --global user.name CircleCI
            - checkout
            - run:
                name: Checkout submodules
                command: git submodule sync && git submodule update --init
            # - restore_cache:
            #     keys:
            #         - npm-deps-{{ checksum "package-lock.json" }}
            #         - npm-deps-
            - run:
                name: Install dependencies
                command: npm install
            # - save_cache:
            #     key: npm-deps-{{ checksum "package-lock.json" }}
            #     paths:
            #         - node_modules
            - run:
                name: Install Hugo
                command: apk update && apk add hugo
            - run:
                name: Mark script as executable
                command: chmod +x ./.circleci/publish_to_ghpages.sh
            - run:
                name: Build and publish site
                command: ./.circleci/publish_to_ghpages.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: develop