version: 2

jobs:
    build:
        docker:
            - image: circleci/node:latest
        working_directory: ~/warframeblog
        steps:
            - run:
                name: Remove git & install dependencies to build git
                command: |
                    sudo apt-get remove git
                    sudo apt-get update
                    sudo apt-get install libcurl4-openssl-dev libexpat1-dev gettext libz-dev libssl-dev build-essential autoconf
            - run:
                name: Build git
                command: |
                    mkdir git-src
                    cd git-src
                    curl -L --progress https://github.com/git/git/archive/v2.7.1.tar.gz | tar xz
                    cd git-2.7.1
                    make configure ./configure && make prefix=/usr/local all
            - run: 
                name: Install git
                command: cd git-src && make prefix=/usr/local install
            - run: git --version
            - add_ssh_keys:
                fingerprint:
                    - "4d:bc:43:fc:36:51:1a:8c:4b:a9:2d:15:a6:8d:d8:34"
            - run: git config --global user.email bot@warframeblog.com
            - run: git config --global user.name CircleCI
            - checkout
            - run: pwd
            - run:
                name: Checkout submodules
                command: git submodule sync && git submodule update --init
            - run: node -v
            - run: npm -v
            - run:
                name: Install dependencies
                command: npm install
            - run:
                name: Install Hugo
                command: wget https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.deb -O /tmp/hugo.deb && sudo dpkg -i /tmp/hugo.deb
            - run:
                name: Mark script as executable
                command: chmod +x ./.circleci/publish_to_ghpages.sh
            - run:
                name: Build and publish site
                command: ./.circleci/publish_to_ghpages.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: develop