version: 2

jobs:
    build:
        docker:
            - image: node:10.16.3-alpine
              environment:
                HUGO_VERSION: 0.58.2
        working_directory: ~/warframeblog
        steps:
            - run:
                name: Update git
                command: apk update && apk add git
            - run: git --version
            - run:
                name: Install OpenSSH
                command: apk update && apk add openssh
            - add_ssh_keys:
                fingerprint:
                    - "4d:bc:43:fc:36:51:1a:8c:4b:a9:2d:15:a6:8d:d8:34"
            - run: git config --global user.email bot@warframeblog.com
            - run: git config --global user.name CircleCI
            - run:
                name: Install Hugo
                command: wget -P /usr/local/hugo/ "https://github.com/spf13/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-64bit.tar.gz" \
                    tar xzf /usr/local/hugo/${HUGO_BINARY}.tar.gz -C /usr/local/hugo/ \
                    && ln -s /usr/local/hugo/hugo /usr/local/bin/hugo \
                    && rm /usr/local/hugo/${HUGO_BINARY}.tar.gz \
                    && hugo version
            - checkout
            - run:
                name: Checkout submodules
                command: git submodule sync && git submodule update --init themes/hesti && git submodule update --init static/wp-content/uploads/2017 && git submodule update --init static/wp-content/uploads/2018
            - run:
                name: Install dependencies
                command: npm install
            - run:
                name: Mark script as executable
                command: chmod +x ./.circleci/publish_to_ghpages.sh
            - run:
                name: Build and publish site
                command: ./.circleci/publish_to_ghpages.sh
    trader_inventory:
        docker:
            - image: node:10.15-alpine
        working_directory: ~/warframeblog
        steps:
            - run:
                name: Update git
                command: apk update && apk add git
            - run: git --version
            - run:
                name: Install OpenSSH
                command: apk update && apk add openssh
            - add_ssh_keys:
                fingerprint:
                    - "4d:bc:43:fc:36:51:1a:8c:4b:a9:2d:15:a6:8d:d8:34"
            - run: git config --global user.email bot@warframeblog.com
            - run: git config --global user.name CircleCI
            - checkout
            - run:
                name: Install dependencies
                command: npm install
            - run:
                name: Load trader inventory
                command: npm run trader:inventory
            - run:
                name: Mark script as executable
                command: chmod +x ./.circleci/commit_to_develop_branch.sh
            - run:
                name: Commit updated trader inventory
                command: ./.circleci/commit_to_develop_branch.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: develop
  update_trader_inventory:
    triggers:
      - schedule:
          cron: "1,3 14,16 * * 0,5"
          filters:
            branches:
              only: develop
    jobs:
      - trader_inventory