version: 2

jobs:
    build:
        branches:
          only:
            - develop
        docker:
            - image: cibuilds/hugo:latest
        working_directory: ~/warframeblog
        steps:
            - run:
                name: Update git
                command: apk update && apk add git
            - run: git --version
            - add_ssh_keys:
                fingerprint:
                    - "4d:bc:43:fc:36:51:1a:8c:4b:a9:2d:15:a6:8d:d8:34"
            - run: git config --global user.email bot@warframeblog.com
            - run: git config --global user.name CircleCI
            - checkout
            - run:
                name: Checkout submodules
                command: git submodule sync && git submodule update --init
            - run:
                name: Mark script as executable
                command: chmod +x ./.circleci/publish_to_ghpages.sh
            - run:
                name: Build and publish site
                command: ./.circleci/publish_to_ghpages.sh